spring:
  application:
    name: mysawit-auth

  datasource:
    url: jdbc:postgresql://localhost:5432/mysawit_auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

server:
  port: 8080

  jwt:
    secret: #TODO
    expiration-ms: #TODO

  google:
    client-id: #TODO